model:
  spk_emb_dim: 192
  win: 512
  stride: 128
  feature_dim: 257
  tcn_blocks: 10
  tcn_layers: 2
  causal: False
  spk_fuse_type: 'multiply'
  use_spk_transform: False

training:
  model_name: 'dpccn'
  load_param_index: -1
  eval_interval: 1
  exp_dir: "exp/dpccn_Test" #the dirname, and the ckpt will be saved in ./Aug4TSE/TSE/exp/dpccn_Test
  loss: 'sisdr'
  num_avg: 5
  accum_grad: 1

optim:
  optimizer: adam
  lr: 0.001
  final_lr: 0.00002
  weight_decay: 0.0001
  lr_descend_factor: 0.98
  patience: 0
  stop_patience: 5
  max_epoch: 150
# Data config
data:
  data_root: "/CDShare3/LibriMix/Libri2Mix/wav16k/min" # the path store the Libri2Mix
  # spk_emb_dir: ["/Work21/2024/huangzikang/Github/Aug4TSE/data_preparation/data/available_embedding/0.5s_TTS_concat"]
  # spk_emb_dir: ["/Work21/2024/huangzikang/Github/Aug4TSE/data_preparation/data/available_embedding/0.5s"]
  spk_emb_dir: ["/Work21/2024/huangzikang/Github/Aug4TSE/TSE/data/enroll_speech/embeddings/LibriSpeech_CAM"] # the path store the {train,valid} enrollment speeches' speaker embeddings
  audio_length: 4
  sample_rate: 16000
  batch_size: 5
  num_workers: 4
  mode: 'mix_clean'
  train_subset: 'train-100'
  valid_subset: 'dev'

# Distribute Training
distribute:
  distributed: False
  gpu_ids: [0]

# gradient clipping
grad_clipping:
  clip_grad: 5.0